//
//  QuestionsAndTestSample.swift
//  FreakQuiz
//
//  Created by Jose Fumanal Quintana on 28/5/21.
//

import Foundation

class QuestionsAndTestSample {
    
    /*var questions: [Question] = [Question(id: 0, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 1, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 2, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 3, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 4, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 5, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 6, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 7, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 8, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 9, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 10, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 11, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 12, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 13, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 14, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 15, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 16, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 17, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 18, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 19, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 20, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 21, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 22, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 23, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 24, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 25, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 26, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 27, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 28, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 29, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 30, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 31, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 32, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 33, mode: 0, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 34, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 35, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 36, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 37, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 38, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 39, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 40, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 41, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 42, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 43, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 44, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 45, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 46, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 47, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 48, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 49, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 50, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 51, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 52, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 53, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 54, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 55, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 56, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 57, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 58, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 59, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 60, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 61, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 62, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 63, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 64, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 65, mode: 1, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 66, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 67, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 68, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 69, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 70, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 71, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 72, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 73, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 74, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 75, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 76, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 77, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 78, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 79, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 80, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 81, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 82, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 83, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 84, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 85, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 86, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 87, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 88, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 89, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 90, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 91, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 92, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 93, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 94, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 95, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 96, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 97, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 98, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>),
                                 Question(id: 99, mode: 2, question: <#T##String#>, options: <#T##[String]?#>, answer: <#T##Int?#>)
    ]*/
    
    var test: [String] = [""]
    
}
